header filter
dubbogo/dubbo-go-proxy pull request #67
Opened 2020-12-04 08:44 UTC by zhangshen023

**What this PR does**:

add header filter so that haeders of http request from client can match headers in resource。

**Does this PR introduce a user-facing change?**:
name: api name
description: api description
resources:
  - path: '/'
    type: restful
    description: resource documentation
    headers:
      header1: value1 # what this pr does
    filters:
      - filter0
    methods:
      - httpVerb: GET
        onAir: true
        inboundRequest:
          requestType: http
          queryStrings:
            - name: id
              required: false
        integrationRequest:
          requestType: dubbo
          mappingParams:
            - name: queryStrings.id
              mapTo: 1
          applicationName: "BDTService"
          interface: "com.ikurento.user.UserProvider"
          method: "GetUser"
          clusterName: "test_dubbo"
```release-note

```

2020-12-04 09:10 UTC, cityiron requested changes

2020-12-04 09:10 UTC, cityiron commented on pkg/filter/header/header.go
> +	"strings"
split

2020-12-04 09:10 UTC, cityiron commented on pkg/router/api.go
> +	Headers       map[string]string `json:"headers" yaml:"headers"`
add omitempty？

2020-12-04 09:10 UTC, cityiron commented on pkg/proxy/listener.go
> +	ctx.AppendFilterFunc(header.New().Do())
one rows with RemoteCallFilter

2020-12-04 09:10 UTC, cityiron commented on pkg/proxy/listener.go
> +	"github.com/dubbogo/dubbo-go-proxy/pkg/filter/header"
split

2020-12-07 02:42 UTC, yqxu approved these changes

2020-12-07 03:13 UTC, cityiron approved these changes

2020-12-07 03:26 UTC, yqxu approved these changes

2020-12-07 07:06 UTC, williamfeng323 commented on pkg/filter/header/header.go
> +func (h *headerFilter) Do() context.FilterFunc {
for struct functions that we don't need to modify the fields within the struct,  should we just 
 define a non-pointer function?

2020-12-07 10:53 UTC, williamfeng323 approved these changes

2020-12-07 12:03 UTC, merged