Add go plugins feature
dubbogo/dubbo-go-proxy pull request #93
Opened 2020-12-27 14:21 UTC by xianlezheng

**What this PR does**:Ftr:Support go plugins with no changes to the project code

**Which issue(s) this PR fixes**:9

Fixes #

**Special notes for your reviewer**: 

**Does this PR introduce a user-facing change?**:

```release-note

```

2020-12-28 02:04 UTC, xiaoliu10 commented on pkg/filter/plugins/plugins.go
> +	"github.com/dubbogo/dubbo-go-proxy/pkg/filter"
split import

2020-12-28 02:05 UTC, xiaoliu10 commented on pkg/filter/plugins/plugins.go
> +	if "" == filePath {
if len(filePath) == 0 ?

2020-12-28 02:08 UTC, xiaoliu10 approved these changes

2020-12-28 02:08 UTC, xiaoliu10 commented on sample/plugins/plugin_test.go
> +	"github.com/dubbogo/dubbo-go-proxy/pkg/context"
split import, thx

2021-01-06 06:05 UTC, mark4z requested changes
configs/plugins/plugin.so should not be included in the project beacuse it's a bin file. Maybe build it in workflows is a better way.

2021-01-06 06:05 UTC, mark4z commented on pkg/filter/plugins/plugins.go
> +	pls, err := plugin.Open(filePath)
configs/plugins/plugin.so should not be included in the project beacuse it's a bin file. Maybe build it in workflows is a better way.

2021-01-08 13:46 UTC, mark4z approved these changes

2021-01-08 13:48 UTC, mark4z approved these changes

2021-01-08 13:49 UTC, mark4z approved these changes
LGTM & I will do it later

2021-01-18 11:10 UTC, cityiron approved these changes

2021-01-18 11:13 UTC, merged